name: Build package

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-package-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build package
    uses: seanthimons/baseline/.github/workflows/build-package.yaml@c99a0a60eed152a08d1e34841d45573fef812af2 # v1.2.0
