name: pkgdown

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
  cancel-in-progress: true

jobs:
  pkgdown:
    name: pkgdown
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: seanthimons/baseline/.github/workflows/pkgdown.yaml@733a6e4554870ab2fa8dd7495fa67bea029bb38c # v1.3.0
