name: pkgdown

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
  cancel-in-progress: true

jobs:
  pkgdown:
    name: pkgdown
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: seanthimons/baseline/.github/workflows/pkgdown.yaml@c99a0a60eed152a08d1e34841d45573fef812af2 # v1.2.0
