name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: r-cmd-check-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  r-cmd-check:
    name: R CMD check
    uses: seanthimons/baseline/.github/workflows/r-cmd-check.yaml@733a6e4554870ab2fa8dd7495fa67bea029bb38c # v1.3.0
    with:
      matrix: >-
        [{"os":"ubuntu-latest","r":"release"},
         {"os":"windows-latest","r":"release"},
         {"os":"macos-latest","r":"release"},
         {"os":"ubuntu-latest","r":"oldrel-1"}]
