name: Test coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: test-coverage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Coverage
    permissions:
      contents: read
      id-token: write
    uses: seanthimons/baseline/.github/workflows/test-coverage.yaml@733a6e4554870ab2fa8dd7495fa67bea029bb38c # v1.3.0
    with:
      codecov: false
      quarto: false
