name: Test coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: test-coverage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Coverage
    permissions:
      contents: read
      id-token: write
    uses: seanthimons/baseline/.github/workflows/test-coverage.yaml@c99a0a60eed152a08d1e34841d45573fef812af2 # v1.2.0
    with:
      codecov: false
      quarto: false
